######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 27 19:47:28 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_LFLAGS += -framework OpenGL -framework GLUT -framework CoreServices

# Input
SOURCES += purff.cpp
